### ISSUE TITLE
pyright crashes when opening a python file

### ISSUE THREAD

**Issue by Araly** [ChristianChiarulli/LunarVim#438]
Hello,

Whenever I try to open a python file, pyright crashes. It gives me a `Client 2 quit with exit code 1 and signal 0` at the bottom of the screen.

`:LspInfo`
```
Configured servers: graphql, tsserver, vimls, html, elixirls, yamlls, efm, bashls, dartls, solargraph, texlab, dockerls, vuels, terraformls, jsonls, angularls, clangd, rust_analyzer, pyright, gopls, intelephense, sumneko_lua, elmls, cssls, svelte, emmet_ls, kotlin_language_server
Neovim logs at: /home/araly/.cache/nvim/lsp.log

1 client(s) attached to this buffer: efm

  Client: efm (id 1)
  	root:      /home/araly/Documents/code/python-project
  	filetypes: lua, python, javascriptreact, javascript, typescript, typescriptreact, sh, html, css, json, yaml, markdown, vue
  	cmd:       /home/araly/.local/share/nvim/lspinstall/efm/efm-langserver
  	


1 active client(s): 

  Client: efm (id 1)
  	root:      /home/araly/Documents/code/python-project
  	filetypes: lua, python, javascriptreact, javascript, typescript, typescriptreact, sh, html, css, json, yaml, markdown, vue
  	cmd:       /home/araly/.local/share/nvim/lspinstall/efm/efm-langserver
  	


Clients that match the filetype python:
  
  Config: efm
  	cmd:               /home/araly/.local/share/nvim/lspinstall/efm/efm-langserver
  	cmd is executable: True
  	identified root:   /home/araly/Documents/code/python-project
  	custom handlers:   
  
  Config: pyright
  	cmd:               /home/araly/.local/share/nvim/lspinstall/python/node_modules/.bin/pyright-langserver --stdio
  	cmd is executable: True
  	identified root:   /home/araly/Documents/code/python-project
  	custom handlers:   textDocument/publishDiagnostics

```

**Comment by rebuilt** [comment]
What's in the log file?  ~/.cache/nvim/lsp.log

Also run :LspStart python.     And then view :messages

**Comment by Araly** [comment]
from a fresh start, I ran `nvim`, opened up a python file in a git project. I then run `:LspStart python`, and in `:messages` I have:
```
Client 2 quit with exit code 1 and signal 0
E5108: Error executing lua ...im/site/pack/packer/opt/nvim-lspconfig/lua/lspconfig.lua:29: attempt to index a nil value
```

in `~/.cache/nvim/lsp.log`
```
[ START ] 2021-05-28T10:11:42+0200 ] LSP logging initiated
[ ERROR ] 2021-05-28T10:11:47+0200 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/araly/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/28 10:11:47 efm-langserver: no configuration file\n2021/05/28 10:11:47 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-05-28T10:11:47+0200 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/araly/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/28 10:11:47 lint for LanguageID not supported: python\n"
[ ERROR ] 2021-05-28T10:11:47+0200 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/araly/.local/share/nvim/lspinstall/python/node_modules/.bin/pyright-langserver"	"stderr"	"internal/modules/cjs/loader.js:638\n    throw err;\n    ^\n\nError: Cannot find module 'worker_threads'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.5013 (/home/araly/.local/share/nvim/lspinstall/python/node_modules/pyright/dist/pyright-langserver.js:1:603)\n    at s (/home/araly/.local/share/nvim/lspinstall/python/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.8863 (/home/araly/.local/share/nvim/lspinstall/python/node_modules/pyright/dist/pyright-internal.js:1:1015416)\n    at s (/home/araly/.local/share/nvim/lspinstall/python/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.5822 (/home/araly/.local/share/nvim/lspinstall/python/node_modules/pyright/dist/pyright-langserver.js:1:48)\n    at s (/home/araly/.local/share/nvim/lspinstall/python/node_modules/pyright/dist/pyright-langserver.js:1:743)\n"
[ ERROR ] 2021-05-28T10:11:58+0200 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/araly/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x55f2ca]\n\ngoroutine 19 ["
[ ERROR ] 2021-05-28T10:11:58+0200 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/araly/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"running]:\ntime.(*Timer).Stop(...)\n\t/usr/local/go/src/time/sleep.go:78\ngithub.com/mattn/efm-langserver/langserver.(*langHandler).handleShutdown(0xc0000ee000, 0x5efd10, 0xc000094000, 0xc0000f2000, 0xc0002240a0, 0x58ff60, 0xc00008afe0, 0xc0000e5d60, 0x5455d4)\n\t/home/araly/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/mattn/efm-langserver@v0.0.29/langserver/handle_shutdown.go:10 +0x2a\ngithub.com/mattn/efm-langserver/langserver.(*langHandler).handle(0xc0000ee000, 0x5efd10, 0xc000094000, 0xc0000f2000, 0xc0002240a0, 0x0, 0x0, 0x0, 0x0)\n\t/home/araly/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/mattn/efm-langserver@v0.0.29/langserver/handler.go:559 +0x19c\ngithub.com/sourcegraph/jsonrpc2.(*HandlerWithErrorConfigurer).Handle(0xc00008a4b0, 0x5efd10, 0xc000094000, 0xc0000f2000, 0xc0002240a0)\n\t/home/araly/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.0.0-20191222043438-96c4efab7ee2/handler_with_error.go:21 +0x72\ngithub.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0xc0000f2000, 0x5efd10, 0xc000094000)\n\t/home/araly/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.0.0-20191222043438-96c4efab7ee2/jsonrpc2.go:522 +0x57e\ncreated by github.com/sourcegraph/jsonrpc2.NewConn\n\t/home/araly/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.0.0-20191222043438-96c4efab7ee2/jsonrpc2.go:334 +0x1d5"
[ ERROR ] 2021-05-28T10:11:58+0200 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/araly/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"\n"
```

**Comment by rebuilt** [comment]
Based on this error "Cannot find module 'worker_threads'".   Try updating your version of nodejs

**Comment by Araly** [comment]
I updated my nodejs from v10.x to v16.x, and everything works now
